### ISSUE TITLE
Printing Diamond pattern

### ISSUE THREAD

**Issue by adarsh786-tech** [pyGuru123/HackPython-21#1]
Hello, I would like to contribute to this repository by adding the source code to print diamond pattern for given value of 'n'. Could you please assign this issue to me.
Thankyou

**Comment by pyGuru123** [comment]
Go for it

**Comment by Durg-PG** [comment]
I would like to add my pattern please

**Comment by pyGuru123** [comment]
Go for it

**Comment by NiranjanMeghwal** [comment]
Hi,
Is [this](https://github.com/NiranjanMeghwal/Python-projects/blob/main/diamond.py) ok?

**Comment by pyGuru123** [comment]
No, try something else
