### ISSUE TITLE
Removed from hacktoberfest?

### ISSUE THREAD

**Issue by alphasingh** [pyGuru123/HackPython-21#307]
On my Hacktoberfest profile, I can see that this repository shows "Excluded Project"
@pyGuru123 can you look into this?
I had my accepted PRs with the needful "hacktoberfest-accepted"
https://github.com/pyGuru123/HackFest21/pulls?q=author%3Aalphasingh

**Comment by alphasingh** [comment]
Anyone else facing the same issue can comment/upvote this.
Goto https://hacktoberfest.digitalocean.com/profile to check if you have got the same issue as mine

**Comment by pyGuru123** [comment]
unfortunately PRs to this repo will not be counted under hacktoberfest, as this repo is excluded due to multiple spam PRs
