### ISSUE TITLE
text 2 speech tool

### ISSUE THREAD

**Issue by pyGuru123** [pyGuru123/HackPython-21#93]
Create a python text 2 speech tool

**Comment by C0mRD** [comment]
Hey !! I want to work on it . Can you please assign me this ?

**Comment by pyGuru123** [comment]
Sure, go for it

**Comment by C0mRD** [comment]
@pyGuru123 Made a PR to fix this issue . 
https://github.com/pyGuru123/HackPython-21/pull/179
Please review it and if eligible please marge it with hacktoberfest-accepted tag .

**Comment by pyGuru123** [comment]
done
