### ISSUE TITLE
PDF Image extractor tool

### ISSUE THREAD

**Issue by pyGuru123** [pyGuru123/HackPython-21#99]
Create a python tool which can extract images from pdf files

**Comment by C0mRD** [comment]
Heyy !! I want to work on this . Can you please assign ?

**Comment by pyGuru123** [comment]
Can you create a GUI application for it.

**Comment by C0mRD** [comment]
@pyGuru123  Yaa !! I definately can . Please assign me this .

**Comment by pyGuru123** [comment]
Sure

**Comment by C0mRD** [comment]
@pyGuru123 Done !! Please check and review it .

**Comment by pyGuru123** [comment]
Coool
